services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/target
      - ~/.ssh:/root/.ssh:ro # SSH鍵の読み取り専用マウント
    environment:
      - DISPLAY=host.docker.internal:0
      - PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
      - RUST_BACKTRACE=1 # デバッグ用のバックトレースを有効化
    platform: linux/amd64 # M1/M2 Mac の場合、エミュレーションを指定
    network_mode: "host" # X11接続を可能に
    stdin_open: true
    tty: true
